import { PurineLevel, FoodCategory } from '@prisma/client'
import { prisma } from '../src/lib/prisma'

type SeedFood = {
  nameTh: string
  nameEn: string
  aliases: string[]
  category: FoodCategory
  purineLevel: PurineLevel
  purinePerHg: number
  unit: string
  source: string
}

const foods: SeedFood[] = [
  { nameTh: 'ธีโอโบรมีน', nameEn: 'Theobromine', aliases: [], category: 'OTHER', purineLevel: 'VERY_HIGH', purinePerHg: 2300.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ยีสต์บริวเวอร์', nameEn: 'Yeast, Brewer\'s', aliases: [], category: 'OTHER', purineLevel: 'VERY_HIGH', purinePerHg: 1810.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ตับอ่อนลูกวัว', nameEn: 'Neck sweet bread, Calf\'s', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'VERY_HIGH', purinePerHg: 1260.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาสแปรตรมควัน', nameEn: 'Sprat, smoked', aliases: [], category: 'SEAFOOD', purineLevel: 'VERY_HIGH', purinePerHg: 804.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ม้ามแกะ', nameEn: 'Sheep\'s spleen', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'VERY_HIGH', purinePerHg: 773.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ยีสต์เบเกอร์', nameEn: 'Yeast, Baker\'s', aliases: [], category: 'OTHER', purineLevel: 'VERY_HIGH', purinePerHg: 680.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ตับวัว', nameEn: 'Ox liver', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'VERY_HIGH', purinePerHg: 554.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หัวใจหมู', nameEn: 'Pig\'s heart', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'VERY_HIGH', purinePerHg: 530.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ม้ามหมู', nameEn: 'Pig\'s spleen', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'VERY_HIGH', purinePerHg: 516.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ตับหมู', nameEn: 'Pig\'s liver', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'VERY_HIGH', purinePerHg: 515.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เห็ดโบลีตัสแห้ง', nameEn: 'Mushroom, flat, edible Boletus, dried', aliases: [], category: 'VEGETABLES', purineLevel: 'VERY_HIGH', purinePerHg: 488.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาซาร์ดีนในน้ำมัน', nameEn: 'Fish, sardines in oil', aliases: [], category: 'SEAFOOD', purineLevel: 'VERY_HIGH', purinePerHg: 480.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ตับลูกวัว', nameEn: 'Liver, Calf\'s', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'VERY_HIGH', purinePerHg: 460.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ม้ามวัว', nameEn: 'Ox spleen', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'VERY_HIGH', purinePerHg: 444.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปอดหมู', nameEn: 'Pig\'s lungs (lights)', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'VERY_HIGH', purinePerHg: 434.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปอดวัว', nameEn: 'Ox lungs (lights)', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'VERY_HIGH', purinePerHg: 399.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาซาร์ดีน', nameEn: 'Fish, sardine, pilchard', aliases: [], category: 'SEAFOOD', purineLevel: 'VERY_HIGH', purinePerHg: 345.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ม้ามลูกวัว', nameEn: 'Spleen, Calf\'s', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'VERY_HIGH', purinePerHg: 343.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไตหมู', nameEn: 'Pig\'s kidney', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'VERY_HIGH', purinePerHg: 334.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาเทราต์', nameEn: 'Fish, trout', aliases: [], category: 'SEAFOOD', purineLevel: 'HIGH', purinePerHg: 297.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาทูน่าในน้ำมัน', nameEn: 'Fish, Tuna in oil', aliases: [], category: 'SEAFOOD', purineLevel: 'HIGH', purinePerHg: 290.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไตวัว', nameEn: 'Ox kidney', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'HIGH', purinePerHg: 269.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาทูน่า', nameEn: 'Fish, Tuna', aliases: [], category: 'SEAFOOD', purineLevel: 'HIGH', purinePerHg: 257.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หัวใจวัว', nameEn: 'Ox heart', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'HIGH', purinePerHg: 256.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ตับไก่', nameEn: 'Liver, chicken', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'HIGH', purinePerHg: 243.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาเรดฟิช', nameEn: 'Fish, Redfish (ocean perch)', aliases: [], category: 'SEAFOOD', purineLevel: 'HIGH', purinePerHg: 241.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หัวใจแกะ', nameEn: 'Heart, Sheep\'s', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'HIGH', purinePerHg: 241.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาแอนโชวี่', nameEn: 'Fish, Anchovy', aliases: [], category: 'SEAFOOD', purineLevel: 'HIGH', purinePerHg: 239.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ถั่วเขียวผิวดำแห้ง', nameEn: 'Black gram (mungo bean), seed, dry', aliases: [], category: 'LEGUMES', purineLevel: 'HIGH', purinePerHg: 222.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาเฮอร์ริ่งหมัก', nameEn: 'Fish, Herring, Matje cured', aliases: [], category: 'SEAFOOD', purineLevel: 'HIGH', purinePerHg: 219.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไตลูกวัว', nameEn: 'Kidney, Calf\'s', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'HIGH', purinePerHg: 218.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาเฮอร์ริ่งแอตแลนติก', nameEn: 'Fish, Herring, Atlantic', aliases: [], category: 'SEAFOOD', purineLevel: 'HIGH', purinePerHg: 210.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อม้า', nameEn: 'Horse meat', aliases: [], category: 'MEAT', purineLevel: 'HIGH', purinePerHg: 200.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ถั่วเหลืองแห้ง', nameEn: 'Bean, Soya, seed, dry', aliases: [], category: 'LEGUMES', purineLevel: 'HIGH', purinePerHg: 190.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไข่ปลาเฮอร์ริ่ง', nameEn: 'Fish, Herring roe', aliases: [], category: 'SEAFOOD', purineLevel: 'HIGH', purinePerHg: 190.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อแกะ', nameEn: 'Lamb (muscles only)', aliases: [], category: 'MEAT', purineLevel: 'HIGH', purinePerHg: 182.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาฮาลิบัต', nameEn: 'Fish, Halibut', aliases: [], category: 'SEAFOOD', purineLevel: 'HIGH', purinePerHg: 178.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'อกไก่พร้อมหนัง', nameEn: 'Chicken (breast with skin)', aliases: [], category: 'POULTRY', purineLevel: 'HIGH', purinePerHg: 175.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อลูกวัว', nameEn: 'Veal, muscles only', aliases: [], category: 'MEAT', purineLevel: 'HIGH', purinePerHg: 172.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาแซลมอน', nameEn: 'Fish, salmon', aliases: [], category: 'SEAFOOD', purineLevel: 'HIGH', purinePerHg: 170.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เมล็ดป๊อปปี้', nameEn: 'Poppy seed, seed, dry', aliases: [], category: 'GRAINS', purineLevel: 'HIGH', purinePerHg: 170.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อหมู (เฉพาะเนื้อ)', nameEn: 'Pork muscles only', aliases: [], category: 'MEAT', purineLevel: 'HIGH', purinePerHg: 166.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ห่าน', nameEn: 'Goose', aliases: [], category: 'POULTRY', purineLevel: 'HIGH', purinePerHg: 165.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไส้กรอกตับ', nameEn: 'Sausage, liver (liverwurst)', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'HIGH', purinePerHg: 165.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาเซธ', nameEn: 'Fish, Saithe (coalfish)', aliases: [], category: 'SEAFOOD', purineLevel: 'HIGH', purinePerHg: 163.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาคาร์ป', nameEn: 'Fish, Carp', aliases: [], category: 'SEAFOOD', purineLevel: 'HIGH', purinePerHg: 160.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ลิ้นวัว', nameEn: 'Ox tongue', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'HIGH', purinePerHg: 160.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ขาหมู', nameEn: 'Pork leg (hind leg)', aliases: [], category: 'MEAT', purineLevel: 'HIGH', purinePerHg: 160.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไก่ต้ม (เฉลี่ย)', nameEn: 'Chicken, boiling fowl, average', aliases: [], category: 'POULTRY', purineLevel: 'HIGH', purinePerHg: 159.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หมูสันใน', nameEn: 'Pork fillet', aliases: [], category: 'MEAT', purineLevel: 'HIGH', purinePerHg: 150.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หมูส่วนไหล่', nameEn: 'Pork shoulder with skin (blade of shoulder)', aliases: [], category: 'MEAT', purineLevel: 'HIGH', purinePerHg: 150.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไก่งวง', nameEn: 'Turkey, young animal, average, with skin', aliases: [], category: 'POULTRY', purineLevel: 'HIGH', purinePerHg: 150.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ขาลูกวัว', nameEn: 'Veal knuckle with bone', aliases: [], category: 'MEAT', purineLevel: 'HIGH', purinePerHg: 150.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'น่องลูกวัว', nameEn: 'Veal, leg of veal with bone', aliases: [], category: 'MEAT', purineLevel: 'HIGH', purinePerHg: 150.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'คอลูกวัว', nameEn: 'Veal, neck with bone', aliases: [], category: 'MEAT', purineLevel: 'HIGH', purinePerHg: 150.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปอดลูกวัว', nameEn: 'Lungs, Calf\'s', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'MODERATE', purinePerHg: 147.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'กุ้ง', nameEn: 'Shrimp, brown', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 147.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาแมคเคอเรล', nameEn: 'Fish, Mackerel', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 145.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หมูชิ้นติดกระดูก', nameEn: 'Pork chop with bone', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 145.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไข่ปลาคาร์เวียร์', nameEn: 'Caviar (real)', aliases: [], category: 'OTHER', purineLevel: 'MODERATE', purinePerHg: 144.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เมล็ดทานตะวัน', nameEn: 'Sunflower seed, dry', aliases: [], category: 'GRAINS', purineLevel: 'MODERATE', purinePerHg: 143.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาไพค์', nameEn: 'Pike', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 140.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หมูส่วนสันคอ', nameEn: 'Pork chuck', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 140.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อลูกวัวติดกระดูก', nameEn: 'Veal chop, cutlet with bone', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 140.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อลูกวัวสันใน', nameEn: 'Veal fillet', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 140.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไหล่ลูกวัว', nameEn: 'Veal, shoulder', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 140.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาแฮดด็อก', nameEn: 'Fish, Haddock', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 139.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อเป็ด', nameEn: 'Duck, average', aliases: [], category: 'POULTRY', purineLevel: 'MODERATE', purinePerHg: 138.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อกวางส่วนขา', nameEn: 'Venison haunch (leg)', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 138.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ลิ้นหมู', nameEn: 'Pig\'s tongue', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'MODERATE', purinePerHg: 136.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หอยเชลล์', nameEn: 'Scallop', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 136.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อวัว (เฉพาะเนื้อ)', nameEn: 'Beef, muscles only', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 133.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อกระต่าย', nameEn: 'Rabbit meat, average with bone', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 132.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาโซล', nameEn: 'Fish, Sole', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 131.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'แฮมสุก', nameEn: 'Ham, cooked', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 131.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ถั่วขาวแห้ง', nameEn: 'Bean, seed, white, dry', aliases: [], category: 'LEGUMES', purineLevel: 'MODERATE', purinePerHg: 128.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ถั่วเลนทิลแห้ง', nameEn: 'Lentil, seed, dry', aliases: [], category: 'LEGUMES', purineLevel: 'MODERATE', purinePerHg: 127.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หมูสามชั้นรมควัน', nameEn: 'Pork belly, raw, smoked dried', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 127.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อวัวส่วนสันคอ', nameEn: 'Beef, chuck', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 120.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อวัวซี่โครง', nameEn: 'Beef, fore rib, entrecote', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 120.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หมูส่วนสะโพก', nameEn: 'Pork hip bone (hind leg)', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 120.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ล็อบสเตอร์', nameEn: 'Lobster', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 118.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไก่ทั้งตัว (เฉลี่ย)', nameEn: 'Chicken (chicken for roasting), average', aliases: [], category: 'POULTRY', purineLevel: 'MODERATE', purinePerHg: 115.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หอยแมลงภู่', nameEn: 'Mussel', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 112.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไส้กรอกยัคท์เวิร์สท์', nameEn: 'Sausage \"Jagdwurst\"', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 112.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อวัวสันใน', nameEn: 'Beef, fillet', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 110.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อวัวย่างสันนอก', nameEn: 'Beef, roast beef, sirloin', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 110.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อวัวส่วนไหล่', nameEn: 'Beef, shoulder', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 110.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'น่องไก่พร้อมหนัง', nameEn: 'Chicken, leg with skin, without bone', aliases: [], category: 'POULTRY', purineLevel: 'MODERATE', purinePerHg: 110.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาไพค์เพิร์ช', nameEn: 'Fish, Pike-perch', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 110.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาค็อด', nameEn: 'Fish, Cod', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 109.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ถั่วลูกไก่แห้ง', nameEn: 'Peas, chick (garbanzo), seed, dry', aliases: [], category: 'LEGUMES', purineLevel: 'MODERATE', purinePerHg: 109.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ลูกเกด', nameEn: 'Grape, dried, raisin, sultana', aliases: [], category: 'FRUITS', purineLevel: 'MODERATE', purinePerHg: 107.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เมล็ดแฟลกซ์', nameEn: 'Linseed', aliases: [], category: 'GRAINS', purineLevel: 'MODERATE', purinePerHg: 105.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'กระต่ายป่า', nameEn: 'Rabbit/Hare (average)', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 105.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อกวางส่วนหลัง', nameEn: 'Venison back', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 105.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ซาลามี่เยอรมัน', nameEn: 'Sausage salami, German', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 104.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไส้กรอกหมูทอด', nameEn: 'Sausages, frying, from pork', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 101.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หมูสามชั้น', nameEn: 'Pork belly', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 100.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ข้าวบาร์เลย์', nameEn: 'Barley without husk, whole grain', aliases: [], category: 'GRAINS', purineLevel: 'MODERATE', purinePerHg: 96.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'มอร์ตาเดลล่า', nameEn: 'Sausage \"Mortadella\"', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 96.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ถั่วลันเตาแห้ง', nameEn: 'Pea, seed, dry', aliases: [], category: 'LEGUMES', purineLevel: 'MODERATE', purinePerHg: 95.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ข้าวโอ๊ต', nameEn: 'Oats, without husk, whole grain', aliases: [], category: 'GRAINS', purineLevel: 'MODERATE', purinePerHg: 94.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาแพลซ', nameEn: 'Plaice', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 93.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'สมองลูกวัว', nameEn: 'Brain, Calf\'s', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'MODERATE', purinePerHg: 92.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เห็ดโบลีตัส', nameEn: 'Mushroom, flat, edible Boletus', aliases: [], category: 'VEGETABLES', purineLevel: 'MODERATE', purinePerHg: 92.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไส้กรอกลูกวัวทอด', nameEn: 'Sausages, frying, from veal', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 91.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หอยนางรม', nameEn: 'Oyster', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 90.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไส้กรอกแฟรงค์เฟิร์ต', nameEn: 'Frankfurter sausages', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 89.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไส้กรอกเบียร์ชิงเก้น', nameEn: 'Sausage \"Bierschincken\"', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 85.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ถั่วลันเตา', nameEn: 'Pea, pod and seed, green', aliases: [], category: 'LEGUMES', purineLevel: 'MODERATE', purinePerHg: 84.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'สมองหมู', nameEn: 'Pig\'s brain', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'MODERATE', purinePerHg: 83.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'บร็อคโคลี่', nameEn: 'Broccoli', aliases: [], category: 'OTHER', purineLevel: 'MODERATE', purinePerHg: 81.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ถั่วงอก', nameEn: 'Bean sprouts, Soya', aliases: [], category: 'LEGUMES', purineLevel: 'MODERATE', purinePerHg: 80.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาเทนช์', nameEn: 'Tench', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 80.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ถั่วลิสง', nameEn: 'Nuts, peanut', aliases: [], category: 'GRAINS', purineLevel: 'MODERATE', purinePerHg: 79.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'อาร์ติโชค', nameEn: 'Artichoke', aliases: [], category: 'VEGETABLES', purineLevel: 'MODERATE', purinePerHg: 78.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ปลาไหลรมควัน', nameEn: 'Fish, eel (smoked)', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 78.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไส้กรอกไฟลช์เวิร์สท์', nameEn: 'Sausage \"Fleischwurst\"', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 78.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไส้กรอกเวียนนา', nameEn: 'Sausage, Vienna', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 78.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'สมองวัว', nameEn: 'Ox brain', aliases: [], category: 'ORGAN_MEAT', purineLevel: 'MODERATE', purinePerHg: 75.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ต้นหอมฝรั่งใหญ่', nameEn: 'Leek', aliases: [], category: 'VEGETABLES', purineLevel: 'MODERATE', purinePerHg: 74.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไส้กรอกเมทท์เวิร์สท์', nameEn: 'Sausages, German (Mettwurst)', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 74.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'แอปริคอท', nameEn: 'Apricot', aliases: [], category: 'FRUITS', purineLevel: 'MODERATE', purinePerHg: 73.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไส้กรอกมิวนิค', nameEn: 'Sausage \"Munich Weisswurst\"', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 73.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ผงโกโก้', nameEn: 'Cocoa powder, oil partially removed', aliases: [], category: 'BEVERAGES', purineLevel: 'MODERATE', purinePerHg: 71.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'แบล็คแซลซิฟาย', nameEn: 'Grass, Viper\'s (black salsify)', aliases: [], category: 'VEGETABLES', purineLevel: 'MODERATE', purinePerHg: 71.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อกระป๋อง', nameEn: 'Meat, luncheon', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 70.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'กะหล่ำดาว', nameEn: 'Brussels sprouts', aliases: [], category: 'OTHER', purineLevel: 'MODERATE', purinePerHg: 69.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เต้าหู้', nameEn: 'Tofu', aliases: [], category: 'LEGUMES', purineLevel: 'MODERATE', purinePerHg: 68.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ต้นหอมฝรั่ง', nameEn: 'Chives', aliases: [], category: 'VEGETABLES', purineLevel: 'MODERATE', purinePerHg: 67.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'มะเดื่อแห้ง', nameEn: 'Fig (dried)', aliases: [], category: 'FRUITS', purineLevel: 'MODERATE', purinePerHg: 64.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ลูกพรุน', nameEn: 'Plum, dried', aliases: [], category: 'FRUITS', purineLevel: 'MODERATE', purinePerHg: 64.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ข้าวฟ่าง', nameEn: 'Millet, shucked corn', aliases: [], category: 'GRAINS', purineLevel: 'MODERATE', purinePerHg: 62.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เมล็ดงา', nameEn: 'Sesame (gingelly) seed, Oriental, dry', aliases: [], category: 'GRAINS', purineLevel: 'MODERATE', purinePerHg: 62.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'กุ้งเครย์ฟิช', nameEn: 'Fish, Crayfish', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 60.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ขนมปังกรอบ', nameEn: 'Crispbread', aliases: [], category: 'GRAINS', purineLevel: 'MODERATE', purinePerHg: 60.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เห็ด', nameEn: 'Mushroom', aliases: [], category: 'VEGETABLES', purineLevel: 'MODERATE', purinePerHg: 58.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'กล้วย', nameEn: 'Banana', aliases: [], category: 'FRUITS', purineLevel: 'MODERATE', purinePerHg: 57.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เนื้อวัวหมัก', nameEn: 'Beef, corned (German)', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 57.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ผักชีฝรั่ง', nameEn: 'Parsley, leaf', aliases: [], category: 'VEGETABLES', purineLevel: 'MODERATE', purinePerHg: 57.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ผักโขม', nameEn: 'Spinach', aliases: [], category: 'VEGETABLES', purineLevel: 'MODERATE', purinePerHg: 57.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'พริกหวานเขียว', nameEn: 'Peppers, green', aliases: [], category: 'VEGETABLES', purineLevel: 'MODERATE', purinePerHg: 55.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'พุดดิ้งเลือด', nameEn: 'Pudding, black', aliases: [], category: 'MEAT', purineLevel: 'MODERATE', purinePerHg: 55.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ข้าวโพดหวาน', nameEn: 'Corn, sweet', aliases: [], category: 'GRAINS', purineLevel: 'MODERATE', purinePerHg: 52.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'กะหล่ำดอก', nameEn: 'Cauliflower', aliases: [], category: 'VEGETABLES', purineLevel: 'MODERATE', purinePerHg: 51.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ข้าวไรย์', nameEn: 'Rye, whole grain', aliases: [], category: 'GRAINS', purineLevel: 'MODERATE', purinePerHg: 51.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ข้าวสาลี', nameEn: 'Wheat, whole grain', aliases: [], category: 'GRAINS', purineLevel: 'MODERATE', purinePerHg: 51.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เห็ดนางฟ้า', nameEn: 'Oyster, mushroom', aliases: [], category: 'SEAFOOD', purineLevel: 'MODERATE', purinePerHg: 50.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'คะน้าฝรั่ง', nameEn: 'Kale', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 48.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ถั่วแขกแห้ง', nameEn: 'Beans, French, dried', aliases: [], category: 'LEGUMES', purineLevel: 'LOW', purinePerHg: 45.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ฟักทอง', nameEn: 'Pumpkin', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 44.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'พาสต้า', nameEn: 'Pasta made with egg (noodles, macaroni, spaghetti', aliases: [], category: 'GRAINS', purineLevel: 'LOW', purinePerHg: 40.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ผักสลัดแลมบ์', nameEn: 'Lettuce, Lamb\'s', aliases: [], category: 'MEAT', purineLevel: 'LOW', purinePerHg: 38.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'อัลมอนด์', nameEn: 'Almond, sweet', aliases: [], category: 'GRAINS', purineLevel: 'LOW', purinePerHg: 37.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ถั่วแขก', nameEn: 'Beans, French (string beans, haricot)', aliases: [], category: 'LEGUMES', purineLevel: 'LOW', purinePerHg: 37.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'กะหล่ำซาวอย', nameEn: 'Cabbage, savoy', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 37.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ถั่วเฮเซลนัท', nameEn: 'Nuts, hazelnut (cobnut)', aliases: [], category: 'GRAINS', purineLevel: 'LOW', purinePerHg: 37.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'อินทผลัม', nameEn: 'Date, dried', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 35.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เอลเดอร์เบอร์รี่', nameEn: 'Elderberry, black', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 33.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เมลอนแคนตาลูป', nameEn: 'Melon, Cantelope', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 33.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'กะหล่ำปลีม่วง', nameEn: 'Cabbage, red', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 32.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ชีสลิมเบอร์เกอร์', nameEn: 'Cheese, Limburger, 20% fat content in dry matter', aliases: [], category: 'DAIRY', purineLevel: 'LOW', purinePerHg: 32.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ขึ้นฉ่ายหัว', nameEn: 'Celeriac', aliases: [], category: 'OTHER', purineLevel: 'LOW', purinePerHg: 30.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เห็ดมอเรล', nameEn: 'Morel', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 30.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ควินซ์', nameEn: 'Quince', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 30.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หน่อไม้', nameEn: 'Bamboo Shoots', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 29.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เห็ดกระป๋อง', nameEn: 'Mushrooms, canned, solid and liquid', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 29.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'มะกอกเขียวดอง', nameEn: 'Olive, green, marinated', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 29.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ผักเครส', nameEn: 'Cress', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 28.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'องุ่น', nameEn: 'Grape', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 27.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'โคห์ลราบี', nameEn: 'Kohlrabi', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 25.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'วอลนัท', nameEn: 'Nuts, Walnut', aliases: [], category: 'GRAINS', purineLevel: 'LOW', purinePerHg: 25.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'พลัม', nameEn: 'Plum', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 24.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'สควอช', nameEn: 'Squash, summer', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 24.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หน่อไม้ฝรั่ง', nameEn: 'Asparagus', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 23.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ถั่วบราซิล', nameEn: 'Nuts, Brazil', aliases: [], category: 'GRAINS', purineLevel: 'LOW', purinePerHg: 23.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'บลูเบอร์รี่', nameEn: 'Bilberry, blueberry, huckleberry', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 22.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'กะหล่ำปลีขาว', nameEn: 'Cabbage, white', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 22.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'มะเขือม่วง', nameEn: 'Aubergine', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 21.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ผักกาดขาว', nameEn: 'Chinese leaves', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 21.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'พีช', nameEn: 'Peach', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 21.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ขนมปังโรล', nameEn: 'Rolls, bread', aliases: [], category: 'GRAINS', purineLevel: 'LOW', purinePerHg: 21.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'สตรอว์เบอร์รี่', nameEn: 'Strawberry', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 21.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'อะโวคาโด', nameEn: 'Avocado', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 19.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'บีทรูท', nameEn: 'Beet root', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 19.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'กีวี่', nameEn: 'Kiwi fruit (Chinese gooseberry, strawberry peach', aliases: [], category: 'POULTRY', purineLevel: 'LOW', purinePerHg: 19.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ส้ม', nameEn: 'Orange', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 19.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'สับปะรด', nameEn: 'Pineapple', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 19.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ไข่ปลาเทียม', nameEn: 'Caviar substitute', aliases: [], category: 'OTHER', purineLevel: 'LOW', purinePerHg: 18.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'มันฝรั่งต้มทั้งเปลือก', nameEn: 'Potato, cooked with skin', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 18.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ราสเบอร์รี่', nameEn: 'Raspberry', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 18.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'แครอท', nameEn: 'Carrot', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 17.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เชอร์รี่เปรี้ยว', nameEn: 'Cherry, Morello', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 17.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ลูกเคอแรนท์แดง', nameEn: 'Currant, red', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 17.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ผักเอนไดว์', nameEn: 'Endive', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 17.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เห็ดแชนเทอเรล', nameEn: 'Mushrooms, Chanterelle', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 17.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เห็ดแชนเทอเรลกระป๋อง', nameEn: 'Mushrooms, Chanterelles, canned, solids & liquids', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 17.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'กูสเบอร์รี่', nameEn: 'Gooseberry', aliases: [], category: 'POULTRY', purineLevel: 'LOW', purinePerHg: 16.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'มันฝรั่ง', nameEn: 'Potato', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 16.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ซาวเคราท์', nameEn: 'Sauerkraut, dripped off', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 16.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หัวไชเท้า', nameEn: 'Radish', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 15.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'แอปเปิ้ล', nameEn: 'Apple', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 14.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เบียร์ไลท์', nameEn: 'Beer, real, light', aliases: [], category: 'BEVERAGES', purineLevel: 'LOW', purinePerHg: 14.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ขนมปังขาว', nameEn: 'Bread, wheat (flour) or (white bread)', aliases: [], category: 'GRAINS', purineLevel: 'LOW', purinePerHg: 14.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ใบเฟนเนล', nameEn: 'Fennel leaves', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 14.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เบียร์พิลสเนอร์', nameEn: 'Beer, Pilsner lager beer, regular beer, German', aliases: [], category: 'BEVERAGES', purineLevel: 'LOW', purinePerHg: 13.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ผักสลัด', nameEn: 'Lettuce', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 13.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'หัวหอม', nameEn: 'Onion', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 13.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'แรดิช', nameEn: 'Radishes', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 13.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ชิคอรี', nameEn: 'Chicory', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 12.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ลูกแพร์', nameEn: 'Pear', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 12.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'รูบาร์บ', nameEn: 'Rhubarb', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 12.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'มะเขือเทศ', nameEn: 'Tomato', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 11.0, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ชีสคอทเทจ', nameEn: 'Cheese, cottage', aliases: [], category: 'DAIRY', purineLevel: 'LOW', purinePerHg: 9.4, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เบียร์ไร้แอลกอฮอล์', nameEn: 'Beer, alcohol free', aliases: [], category: 'BEVERAGES', purineLevel: 'LOW', purinePerHg: 8.1, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'โยเกิร์ต', nameEn: 'Yogurt, min. 3.5% fat content', aliases: [], category: 'BEVERAGES', purineLevel: 'LOW', purinePerHg: 8.1, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'แตงกวา', nameEn: 'Cucumber', aliases: [], category: 'VEGETABLES', purineLevel: 'LOW', purinePerHg: 7.3, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ชีสบรี', nameEn: 'Cheese, Brie', aliases: [], category: 'DAIRY', purineLevel: 'LOW', purinePerHg: 7.1, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ชีสเอดัม 30%', nameEn: 'Cheese, edam, 30% fat content in dry matter', aliases: [], category: 'DAIRY', purineLevel: 'LOW', purinePerHg: 7.1, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ชีสเอดัม 40%', nameEn: 'Cheese, edam, 40% fat content in dry matter', aliases: [], category: 'DAIRY', purineLevel: 'LOW', purinePerHg: 7.1, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ชีสเอดัม 45%', nameEn: 'Cheese, edam, 45% fat content in dry matter', aliases: [], category: 'DAIRY', purineLevel: 'LOW', purinePerHg: 7.1, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'เชอร์รี่หวาน', nameEn: 'Cherry, sweet', aliases: [], category: 'FRUITS', purineLevel: 'LOW', purinePerHg: 7.1, unit: 'g', source: 'Purine Table PDF' },
  { nameTh: 'ชีสเชดดาร์', nameEn: 'Cheese, Cheddar/Cheshire cheese, 50% fat content', aliases: [], category: 'DAIRY', purineLevel: 'LOW', purinePerHg: 6.0, unit: 'g', source: 'Purine Table PDF' },
]

async function main() {
  console.log('Start seeding...')
  await prisma.food.deleteMany({})
  for (const food of foods) {
    await prisma.food.create({
      data: {
        ...food,
        isVerified: true,
      },
    })
  }
  console.log(`Seeded ${foods.length} foods successfully.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
